"""update users table

Revision ID: cc609e9c3730
Revises: ad6efae210a1
Create Date: 2026-05-03 04:05:08.139814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cc609e9c3730"
down_revision: Union[str, Sequence[str], None] = "ad6efae210a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("location", sa.String(), nullable=True))
    op.add_column("users", sa.Column("about_me", sa.String(), nullable=True))
    op.add_column("users", sa.Column("skills", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "skills")
    op.drop_column("users", "about_me")
    op.drop_column("users", "location")
    # ### end Alembic commands ###
